table Date
	lineageTag: 3e9fd7dd-aadf-49b5-8766-7a5d3897ecf2

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0de63644-f2a0-4533-a269-8e4db17df19c
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Relative Num'
		dataType: double
		lineageTag: 3d6c8ca7-0327-4c90-a3a3-89287312c8af
		summarizeBy: sum
		sourceColumn: Date Relative Num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 0cf007c4-da8c-4f99-8558-51c44de205cc
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Year Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9eacc32b-eca1-4877-8832-d0e59bf7eaad
		summarizeBy: none
		sourceColumn: Year Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Year Relative Num'
		dataType: int64
		formatString: 0
		lineageTag: 6dd13262-6fa7-46d7-9fba-e35b60f54b6c
		summarizeBy: sum
		sourceColumn: Year Relative Num

		annotation SummarizationSetBy = Automatic

	column 'Fis Year'
		dataType: int64
		formatString: 0
		lineageTag: 15722756-7bcc-4c29-8e6b-19462ba5b4d9
		summarizeBy: sum
		sourceColumn: Fis Year

		annotation SummarizationSetBy = Automatic

	column 'Fis Year Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0609632f-1918-4099-ae54-337f6c7b0323
		summarizeBy: none
		sourceColumn: Fis Year Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fis Year Relative Num'
		dataType: int64
		formatString: 0
		lineageTag: 864c3c32-d77e-48d4-8367-bd2623dddb17
		summarizeBy: sum
		sourceColumn: Fis Year Relative Num

		annotation SummarizationSetBy = Automatic

	column 'Qtr Num'
		dataType: int64
		formatString: 0
		lineageTag: 904a6105-d17d-446d-9016-563275f26e52
		summarizeBy: sum
		sourceColumn: Qtr Num

		annotation SummarizationSetBy = Automatic

	column Qtr
		dataType: string
		lineageTag: bf64b4a2-7cbe-4e35-9a7a-239c2b481c59
		summarizeBy: none
		sourceColumn: Qtr

		annotation SummarizationSetBy = Automatic

	column 'Qtr qq-yy'
		dataType: string
		lineageTag: ab3d3bfa-4a7a-4e55-bc7e-a86f876a0ece
		summarizeBy: none
		sourceColumn: Qtr qq-yy

		annotation SummarizationSetBy = Automatic

	column 'Qtr Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 34c18144-438c-4c1f-8912-066dab50dee0
		summarizeBy: none
		sourceColumn: Qtr Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fis Qtr Num'
		dataType: double
		lineageTag: 27af56c9-3362-42a7-82a3-892b90992759
		summarizeBy: sum
		sourceColumn: Fis Qtr Num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fis Qtr'
		dataType: string
		lineageTag: 56d38860-f693-4d54-a16d-13b17b23c185
		summarizeBy: none
		sourceColumn: Fis Qtr

		annotation SummarizationSetBy = Automatic

	column 'Fis Qtr Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 44c1a54d-024b-44c4-9254-0cdcf88ccec7
		summarizeBy: none
		sourceColumn: Fis Qtr Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fis Qtr qq-yy'
		dataType: string
		lineageTag: a8a8ad4c-b989-41fd-b726-9cb9017c3f98
		summarizeBy: none
		sourceColumn: Fis Qtr qq-yy

		annotation SummarizationSetBy = Automatic

	column 'Qtr Relative Num'
		dataType: double
		lineageTag: 63eb691a-957e-47c3-963b-81f238ccf09a
		summarizeBy: sum
		sourceColumn: Qtr Relative Num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Num'
		dataType: int64
		formatString: 0
		lineageTag: c008bf9b-7664-4b0f-b346-23ef584666d4
		summarizeBy: sum
		sourceColumn: Month Num

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 835bd4e6-9e46-49bc-839b-0b71ed980354
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Month mmm-yyyy'
		dataType: string
		lineageTag: ddc5bbcc-2c8d-43bc-a2fc-c5583b10b213
		summarizeBy: none
		sourceColumn: Month mmm-yyyy

		annotation SummarizationSetBy = Automatic

	column 'Month Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5fa22436-637a-4fdc-9d17-64f441b47d77
		summarizeBy: none
		sourceColumn: Month Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fis Month Num'
		dataType: int64
		formatString: 0
		lineageTag: f26496a7-66e0-48b1-a35a-271abdc4a578
		summarizeBy: sum
		sourceColumn: Fis Month Num

		annotation SummarizationSetBy = Automatic

	column 'Fis Month mmm-yyyy'
		dataType: string
		lineageTag: b3412c88-5a64-4ede-a79c-0286d6c4883e
		summarizeBy: none
		sourceColumn: Fis Month mmm-yyyy

		annotation SummarizationSetBy = Automatic

	column 'Fis Month Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b1d1c93a-6f72-4bcc-aa7e-185a48b557ee
		summarizeBy: none
		sourceColumn: Fis Month Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fis Month'
		dataType: string
		lineageTag: dd89a99a-06b6-42e2-958e-c66aa734cab1
		summarizeBy: none
		sourceColumn: Fis Month

		annotation SummarizationSetBy = Automatic

	column 'Month Relative Num'
		dataType: double
		lineageTag: 2aa45ea7-8f05-4fba-8b43-3c88116308ba
		summarizeBy: sum
		sourceColumn: Month Relative Num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week of Year (USA)'
		dataType: double
		lineageTag: 4bdda673-75bf-403d-be3a-97f3feb9bbdf
		summarizeBy: sum
		sourceColumn: Week of Year (USA)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9520cf43-b727-428b-86c3-3932d655dd07
		summarizeBy: none
		sourceColumn: Week Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fis Week Of Year (USA)'
		dataType: double
		lineageTag: c60717e9-78a7-4414-90b5-bca9b7bbdad0
		summarizeBy: sum
		sourceColumn: Fis Week Of Year (USA)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week Relative'
		dataType: double
		lineageTag: c519d7cf-75b4-41d1-89ea-edb6bd1551fe
		summarizeBy: sum
		sourceColumn: Week Relative

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of Week'
		dataType: string
		lineageTag: 21253c7d-762b-4df5-bd74-e3a98e16727d
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column 'Day of Wk Num'
		dataType: int64
		formatString: 0
		lineageTag: 94afdf6f-f6b1-46d1-858a-21cc1737bd65
		summarizeBy: sum
		sourceColumn: Day of Wk Num

		annotation SummarizationSetBy = Automatic

	column 'Weekday Flag'
		dataType: int64
		formatString: 0
		lineageTag: ffee2f5f-721d-4235-b2a7-bec04be2be9c
		summarizeBy: sum
		sourceColumn: Weekday Flag

		annotation SummarizationSetBy = Automatic

	column 'Weekday Label'
		dataType: string
		lineageTag: a1debd44-4d9e-4a65-bcc5-c6a605708f34
		summarizeBy: none
		sourceColumn: Weekday Label

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		source = ```
				let
				    #"»»»» Table Setup ««««" = Table.FromRecords( { [] } ),
				    // Which day should the calendar start on?
				    // #date(2019, 7, 1) for Jul 1st 2019
				    #"SET start date" = Table.AddColumn(#"»»»» Table Setup ««««", "Start", each #date( 1964, 1, 1 )),
				    // How many years past the current calendar year should this run?
				    #"SET years past current" = Table.AddColumn(#"SET start date", "Years Past Current", each 1),
				    // What day of the week is the first?
				    #"SET first day of week" = Table.AddColumn(#"SET years past current", "First Day of Wk Num", each Day.Sunday),
				    // Which month of the calendar year does the fiscal year start on?
				    #"SET first month of fiscal" = Table.AddColumn(#"SET first day of week","FirstMonthOfFiscal", each 7),
				    #"»»»» (End Setup) ««««" = #"SET first month of fiscal",
				    #"----------------" = #"»»»» (End Setup) ««««",
				    #"--Build Dates--" = #"----------------",
				    #"DEFINE first month of fiscal" = Table.AddColumn(#"--Build Dates--", "LastMonthOfFiscal", each Number.Mod( [FirstMonthOfFiscal] + 10, 12 ) + 1 ),
				    #"DEFINE end" = Table.AddColumn(#"DEFINE first month of fiscal", "End", each Date.AddYears(
				    Date.EndOfYear(
				        Date.From(
				            DateTime.FixedLocalNow()
				        )
				    ),
				    [Years Past Current]
				), type date ),
				    #"DEFINE date" = Table.AddColumn(#"DEFINE end", "Date", each
				List.Dates(
				    [Start],
				    Number.From( [End] - [Start] ) + 1,
				    Duration.From(1)
				)
				),
				    #"KEEP essential columns" = Table.SelectColumns(#"DEFINE date",{"First Day of Wk Num", "LastMonthOfFiscal", "FirstMonthOfFiscal", "Date"}),
				    #"EXPAND date" = Table.ExpandListColumn(#"KEEP essential columns", "Date"),
				    #"CAST as date" = Table.TransformColumnTypes(#"EXPAND date",{{"Date", type date}, {"LastMonthOfFiscal", Int64.Type}, {"FirstMonthOfFiscal", Int64.Type}}),
				    #"--Add Helper Columns--" = #"CAST as date",
				    #"DEFINE date fis equiv" = Table.AddColumn(#"--Add Helper Columns--", "FisRefDate", each Date.AddMonths( [Date], 12 - [LastMonthOfFiscal] )),
				    #"--Date Columns--" = #"DEFINE date fis equiv",
				    #"ADD date relative" = Table.AddColumn(#"--Date Columns--", "Date Relative Num", each Duration.Days( 
				    [Date] - 
				    Date.From( DateTime.FixedLocalNow() ) 
				), type number),
				    #"--Year Columns--" = #"ADD date relative",
				    #"ADD year" = Table.AddColumn(#"--Year Columns--", "Year", each Date.Year([Date]), Int64.Type),
				    #"ADD year start date" = Table.AddColumn(#"ADD year", "Year Start Date", each Date.StartOfYear([Date]), type date),
				    #"ADD year relative num" = Table.AddColumn(#"ADD year start date", "Year Relative Num", each Date.Year([Date]) - 
				Date.Year(DateTime.From(DateTime.FixedLocalNow())), Int64.Type),
				    #"ADD fis year" = Table.AddColumn(#"ADD year relative num", "Fis Year", each Date.Year([FisRefDate]), Int64.Type),
				    #"ADD fis year start date" = Table.AddColumn(#"ADD fis year", "Fis Year Start Date", each 
				Date.AddMonths( Date.StartOfYear([FisRefDate]) , -1 * (12 - [LastMonthOfFiscal] ) )
				
				, type date),
				    #"ADD fis year relative num" = Table.AddColumn(#"ADD fis year start date", "Fis Year Relative Num", each [
				vrSysDate = Date.From(DateTime.FixedLocalNow()),
				vrLastMonFY = [LastMonthOfFiscal], 
				
				vrSysEquivDate = 
				    Date.AddMonths( 
				        vrSysDate, 
				        12 - vrLastMonFY 
				    ),
				vrSysFY = Date.Year( vrSysEquivDate ),
				vrRowFY = Date.Year([FisRefDate]),
				vrRelativeFY = vrRowFY - vrSysFY
				][vrRelativeFY], Int64.Type),
				    #"--Qtr Columns--" = #"ADD fis year relative num",
				    #"ADD quarter num" = Table.AddColumn(#"--Qtr Columns--", "Qtr Num", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"ADD quarter" = Table.AddColumn(#"ADD quarter num", "Qtr", each "Q" & Text.From( Date.QuarterOfYear([Date]) ), type text),
				    #"ADD qtr qq-yy" = Table.AddColumn(#"ADD quarter", "Qtr qq-yy", each 
				"Q" & Text.From( Date.QuarterOfYear([Date]) ) & 
				"-" & Date.ToText([Date], "yy"), type text),
				    #"ADD qtr start" = Table.AddColumn(#"ADD qtr qq-yy", "Qtr Start Date", each Date.StartOfQuarter([Date]), type date),
				    #"ADD fis qtr num" = Table.AddColumn(#"ADD qtr start", "Fis Qtr Num", each Date.QuarterOfYear( [FisRefDate] ), type number),
				    #"ADD fis qtr" = Table.AddColumn(#"ADD fis qtr num", "Fis Qtr", each "Q" & Text.From( Date.QuarterOfYear( [FisRefDate]) ), type text),
				    #"ADD fis qtr start date" = Table.AddColumn(#"ADD fis qtr", "Fis Qtr Start Date", each Date.StartOfQuarter([Date]), type date),
				    #"ADD fis qtr qq-yy" = Table.AddColumn(#"ADD fis qtr start date", "Fis Qtr qq-yy", each "Q" & Text.From( Date.QuarterOfYear( [FisRefDate] ) ) & 
				"-" & Date.ToText( [FisRefDate], "yy"), type text),
				    #"ADD qtr relative num" = Table.AddColumn(#"ADD fis qtr qq-yy", "Qtr Relative Num", each
				(
				    Date.Year(Date.From([Date])) * 4 + 
				    Date.QuarterOfYear(Date.From([Date])) 
				) -
				(
				    Date.Year(Date.From(DateTime.FixedLocalNow())) * 4 + 
				    Date.QuarterOfYear(Date.From(DateTime.FixedLocalNow())) 
				),
				type number),
				    #"--Month Columns--" = #"ADD qtr relative num",
				    #"ADD month num" = Table.AddColumn(#"--Month Columns--", "Month Num", each Date.Month([Date]), Int64.Type),
				    #"ADD month" = Table.AddColumn(#"ADD month num", "Month", each Date.ToText( [Date], "MMM" ), type text),
				    #"ADD month mmm-yyyy" = Table.AddColumn(#"ADD month", "Month mmm-yyyy", each Date.ToText( [Date], "MMM-yyyy" ), type text),
				    #"ADD month start date" = Table.AddColumn(#"ADD month mmm-yyyy", "Month Start Date", each Date.StartOfMonth([Date]), type date),
				    #"ADD fis month num" = Table.AddColumn(#"ADD month start date", "Fis Month Num", each Date.Month([FisRefDate]), Int64.Type),
				    #"ADD fis month mmm-yyyy" = Table.AddColumn(#"ADD fis month num", "Fis Month mmm-yyyy", each Date.ToText( [Date], "MMM" ) & "-" & Date.ToText( [FisRefDate], "yyyy" ), type text),
				    #"ADD fis month start date" = Table.AddColumn(#"ADD fis month mmm-yyyy", "Fis Month Start Date", each Date.StartOfMonth([Date]), type date),
				    #"ADD fis month" = Table.AddColumn(#"ADD fis month start date", "Fis Month", each Date.ToText( [Date], "MMM" ), type text),
				    #"ADD relative month num" = Table.AddColumn(#"ADD fis month", "Month Relative Num", each 
				( Date.Year([Date]) * 12 + Date.Month([Date]) )- 
				( Date.Year( Date.From( DateTime.FixedLocalNow() ) ) * 12 + Date.Month(Date.From( DateTime.FixedLocalNow() )) )
				, type number),
				    #"--Week Columns--" = #"ADD relative month num",
				    #"ADD wk of year usa" = Table.AddColumn(#"--Week Columns--", "Week of Year (USA)", each [
				//Get the assumptions
				vrRowDate  = [Date],
				vrYrStartMon = [FirstMonthOfFiscal],
				vrDowStart = [First Day of Wk Num],
				
				//Figure out the FisYrs start date for this row
				vrRowYear  = Date.Year( vrRowDate ),
				vrRefDateRaw = #date( vrRowYear, 1, 1 ),
				
				//Get the first day of the week for each
				vrYrWkStart = Date.StartOfWeek( vrRefDateRaw, vrDowStart ),
				vrRowWkStart = Date.StartOfWeek( vrRowDate, vrDowStart ),
				
				//Get the days between and divide by 7 to get wks between.
				vrWeekNum = 
				    Duration.Days(  vrRowWkStart - vrYrWkStart ) 
				    / 7 
				    + 1
				][vrWeekNum], type number),
				    #"ADD we start date" = Table.AddColumn(#"ADD wk of year usa", "Week Start Date", each Date.StartOfWeek([Date], [First Day of Wk Num]), type date),
				    #"ADD fis wk of year usa" = Table.AddColumn(#"ADD we start date", "Fis Week Of Year (USA)", each [
				//Get the assumptions
				vrRowDate  = [Date],
				vrYrStartMon = [FirstMonthOfFiscal],
				vrDowStart = [First Day of Wk Num],
				
				//Figure out the FisYrs start date for this row
				vrRowMonth = Date.Month( vrRowDate ),
				vrRowYear  = Date.Year( vrRowDate ),
				vrDateInCurrCalYear = ( vrRowMonth >= vrYrStartMon ),
				vrRefDateRaw =
				    if   vrDateInCurrCalYear
				    then #date( vrRowYear,     vrYrStartMon, 1 )
				    else #date( vrRowYear - 1, vrYrStartMon, 1 ),
				
				//Get the first day of the week for each
				vrYrWkStart = Date.StartOfWeek( vrRefDateRaw, vrDowStart ),
				vrRowWkStart = Date.StartOfWeek( vrRowDate, vrDowStart ),
				
				//Get the days between and divide by 7 to get wks between.
				vrWeekNum = 
				    Duration.Days(  vrRowWkStart - vrYrWkStart ) 
				    / 7 
				    + 1
				][vrWeekNum], type number),
				    #"ADD wk relative" = Table.AddColumn(#"ADD fis wk of year usa", "Week Relative", each [
				vrRowDate = [Date],
				vrSysDate = Date.From( DateTime.FixedLocalNow() ),
				vrWeeksStart = [First Day of Wk Num],
				
				vrRowWkStart = Date.StartOfWeek( vrRowDate, vrWeeksStart ),
				vrSysWkStart = Date.StartOfWeek( vrSysDate, vrWeeksStart ),
				vrRelativeWeek = 
				    Duration.Days( vrRowWkStart - vrSysWkStart ) / 7
				][vrRelativeWeek], type number),
				    #"ADD day of wk name" = Table.AddColumn(#"ADD wk relative", "Day of Week", each Date.ToText([Date], "ddd"), type text),
				    #"ADD day of wk num" = Table.AddColumn(#"ADD day of wk name", "Day of Wk Num", each Date.DayOfWeek( [Date], [First Day of Wk Num] ) + 1, Int64.Type),
				    #"ADD weekday flag" = Table.AddColumn(#"ADD day of wk num", "Weekday Flag", each if Date.DayOfWeek( [Date], Day.Monday ) <= 4
				then 1
				else 0, Int64.Type),
				    #"ADD weekday label" = Table.AddColumn(#"ADD weekday flag", "Weekday Label", each if Date.DayOfWeek( [Date], Day.Monday ) <= 4
				then "Weekday"
				else "Weekend", type text),
				    #"DELETE helper columns" = Table.RemoveColumns(#"ADD weekday label",{"First Day of Wk Num", "LastMonthOfFiscal", "FirstMonthOfFiscal", "FisRefDate"}),
				    #"--Keep Reorder Rename--" = #"DELETE helper columns"
				in
				    #"--Keep Reorder Rename--"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

