table 'Date (Report End)'
	lineageTag: 6e60136b-68bb-4f42-8282-dbf45b7879a7
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 2393cb48-f0cf-4a02-9b74-b15c7c9a17ec
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Relative Num'
		dataType: double
		lineageTag: a007857f-8790-4578-abd1-a2f1ed60d24d
		summarizeBy: sum
		sourceColumn: Date Relative Num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 83da794a-0665-4d3c-ac5f-5e7739774538
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Year Start Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: da58eec7-8ae7-41e9-98f1-01117496bad6
		summarizeBy: none
		sourceColumn: Year Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Year Relative Num'
		dataType: int64
		formatString: 0
		lineageTag: 5196364e-68fb-46fc-bba9-c3662482369e
		summarizeBy: sum
		sourceColumn: Year Relative Num

		annotation SummarizationSetBy = Automatic

	column 'Fis Year'
		dataType: int64
		formatString: 0
		lineageTag: 2f4df6a5-02b2-4628-bbcf-07b16e44c6d3
		summarizeBy: sum
		sourceColumn: Fis Year

		annotation SummarizationSetBy = Automatic

	column 'Fis Year Start Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 08b223ef-02ec-43d3-913f-209fb2ed25f1
		summarizeBy: none
		sourceColumn: Fis Year Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fis Year Relative Num'
		dataType: int64
		formatString: 0
		lineageTag: 24a93ea3-0792-40fc-a6a1-8080ac5ed721
		summarizeBy: sum
		sourceColumn: Fis Year Relative Num

		annotation SummarizationSetBy = Automatic

	column 'Qtr Num'
		dataType: int64
		formatString: 0
		lineageTag: cd69ee45-2faa-42eb-8f39-a3e6a07e71ce
		summarizeBy: sum
		sourceColumn: Qtr Num

		annotation SummarizationSetBy = Automatic

	column Qtr
		dataType: string
		lineageTag: b6c8c4c1-133a-47ca-aa19-96ccd28b261d
		summarizeBy: none
		sourceColumn: Qtr

		annotation SummarizationSetBy = Automatic

	column 'Qtr qq-yy'
		dataType: string
		lineageTag: 7eabcec5-8c0a-4ecf-bef8-a45bbb033a94
		summarizeBy: none
		sourceColumn: Qtr qq-yy

		annotation SummarizationSetBy = Automatic

	column 'Qtr Start Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3de899d8-2979-40a2-b9d0-444f2fa1d4be
		summarizeBy: none
		sourceColumn: Qtr Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fis Qtr Num'
		dataType: double
		lineageTag: 1d25760c-8dbb-42c5-b559-861f4973acbc
		summarizeBy: sum
		sourceColumn: Fis Qtr Num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fis Qtr'
		dataType: string
		lineageTag: a6b38e47-5737-4361-ae3f-c523e21da2d9
		summarizeBy: none
		sourceColumn: Fis Qtr

		annotation SummarizationSetBy = Automatic

	column 'Fis Qtr Start Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5d7459b9-a9fa-456b-8561-2004d41b64e4
		summarizeBy: none
		sourceColumn: Fis Qtr Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fis Qtr qq-yy'
		dataType: string
		lineageTag: 81057c89-c3c8-4c32-9d2a-db67e5cb099d
		summarizeBy: none
		sourceColumn: Fis Qtr qq-yy
		sortByColumn: 'Fis Qtr Start Date'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Qtr Relative Num'
		dataType: double
		lineageTag: a4fda867-0363-42ab-a87b-13777ce27765
		summarizeBy: sum
		sourceColumn: Qtr Relative Num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Num'
		dataType: int64
		formatString: 0
		lineageTag: 6c2f2bcf-bc2b-4a9a-a641-a538ecda59ff
		summarizeBy: sum
		sourceColumn: Month Num

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 48ecaaff-fcad-4441-8778-6287fd2de11e
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Month mmm-yyyy'
		dataType: string
		lineageTag: cf56cb2f-f88b-4ecf-a558-5f4067c33769
		summarizeBy: none
		sourceColumn: Month mmm-yyyy

		annotation SummarizationSetBy = Automatic

	column 'Month Start Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 475a1fb7-ee56-4a42-a734-a426d7f8f23e
		summarizeBy: none
		sourceColumn: Month Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fis Month Num'
		dataType: int64
		formatString: 0
		lineageTag: 9aa31559-b698-43ac-a65c-51fea53fedc1
		summarizeBy: sum
		sourceColumn: Fis Month Num

		annotation SummarizationSetBy = Automatic

	column 'Fis Month mmm-yyyy'
		dataType: string
		lineageTag: 37505c56-b29a-4bee-ba14-001c6b6617fa
		summarizeBy: none
		sourceColumn: Fis Month mmm-yyyy

		annotation SummarizationSetBy = Automatic

	column 'Fis Month Start Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 653b941c-a76e-4280-bb5d-7f5e35d59c1b
		summarizeBy: none
		sourceColumn: Fis Month Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fis Month'
		dataType: string
		lineageTag: 23e35080-5d97-4b91-904c-2de4b8eb0993
		summarizeBy: none
		sourceColumn: Fis Month

		annotation SummarizationSetBy = Automatic

	column 'Month Relative Num'
		dataType: double
		lineageTag: d86d61cf-96f7-46a0-906e-4db586c243f1
		summarizeBy: sum
		sourceColumn: Month Relative Num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week of Year (USA)'
		dataType: double
		lineageTag: 87b55e05-0c68-4309-b396-a923956f9426
		summarizeBy: sum
		sourceColumn: Week of Year (USA)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week Start Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0ffd60fc-c0cf-4e2d-a6c4-84dd73b84468
		summarizeBy: none
		sourceColumn: Week Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fis Week Of Year (USA)'
		dataType: double
		lineageTag: d8abf526-e5d6-4a52-9e9f-b817f6d13dec
		summarizeBy: sum
		sourceColumn: Fis Week Of Year (USA)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week Relative'
		dataType: double
		lineageTag: 66040d79-c962-4ef0-b4c9-187f6d1f77ef
		summarizeBy: sum
		sourceColumn: Week Relative

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of Week'
		dataType: string
		lineageTag: 69a41b81-8d1a-4022-b926-bc63a52d7ed7
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column 'Day of Wk Num'
		dataType: int64
		formatString: 0
		lineageTag: 4ddeb237-20e3-492b-b590-ea2f6a113c81
		summarizeBy: sum
		sourceColumn: Day of Wk Num

		annotation SummarizationSetBy = Automatic

	column 'Weekday Flag'
		dataType: int64
		formatString: 0
		lineageTag: 61dc1608-05f0-4e62-b0bc-ee93da3dba3e
		summarizeBy: sum
		sourceColumn: Weekday Flag

		annotation SummarizationSetBy = Automatic

	column 'Weekday Label'
		dataType: string
		lineageTag: 24fc5220-6a35-4f4b-bd8b-7f441b65bd82
		summarizeBy: none
		sourceColumn: Weekday Label

		annotation SummarizationSetBy = Automatic

	partition 'Date (Report End)' = m
		mode: import
		source = ```
				//Calendarfornia Dreamin - Brian Grant - 2020-05-08 0901
				let
				    #"»»»» Table Setup ««««" = Table.FromRecords( { [] } ),
				    // Which day should the calendar start on?
				    // #date(2019, 7, 1) for Jul 1st 2019
				    #"SET start date" = Table.AddColumn(#"»»»» Table Setup ««««", "Start", each #date( 2019, 7, 1 )),
				    // How many years past the current calendar year should this run?
				    #"SET years past current" = Table.AddColumn(#"SET start date", "Years Past Current", each 0),
				    // What day of the week is the first?
				    #"SET first day of week" = Table.AddColumn(#"SET years past current", "First Day of Wk Num", each Day.Sunday),
				    // Which month of the calendar year does the fiscal year start on?
				    #"SET first month of fiscal" = Table.AddColumn(#"SET first day of week","FirstMonthOfFiscal", each 7),
				    #"»»»» (End Setup) ««««" = #"SET first month of fiscal",
				    #"----------------" = #"»»»» (End Setup) ««««",
				    #"--Build Dates--" = #"----------------",
				    #"DEFINE first month of fiscal" = Table.AddColumn(#"--Build Dates--", "LastMonthOfFiscal", each Number.Mod( [FirstMonthOfFiscal] + 10, 12 ) + 1 ),
				    #"DEFINE end" = Table.AddColumn(#"DEFINE first month of fiscal", "End", each Date.AddYears(
				    Date.EndOfYear(
				        Date.From(
				            DateTime.FixedLocalNow()
				        )
				    ),
				    [Years Past Current]
				), type date ),
				    #"DEFINE date" = Table.AddColumn(#"DEFINE end", "Date", each
				List.Dates(
				    [Start],
				    Number.From( [End] - [Start] ) + 1,
				    Duration.From(1)
				)
				),
				    #"KEEP essential columns" = Table.SelectColumns(#"DEFINE date",{"First Day of Wk Num", "LastMonthOfFiscal", "FirstMonthOfFiscal", "Date"}),
				    #"EXPAND date" = Table.ExpandListColumn(#"KEEP essential columns", "Date"),
				    #"CAST as date" = Table.TransformColumnTypes(#"EXPAND date",{{"Date", type date}, {"LastMonthOfFiscal", Int64.Type}, {"FirstMonthOfFiscal", Int64.Type}}),
				    #"--Add Helper Columns--" = #"CAST as date",
				    #"DEFINE date fis equiv" = Table.AddColumn(#"--Add Helper Columns--", "FisRefDate", each Date.AddMonths( [Date], 12 - [LastMonthOfFiscal] )),
				    #"--Date Columns--" = #"DEFINE date fis equiv",
				    #"ADD date relative" = Table.AddColumn(#"--Date Columns--", "Date Relative Num", each Duration.Days( 
				    [Date] - 
				    Date.From( DateTime.FixedLocalNow() ) 
				), type number),
				    #"--Year Columns--" = #"ADD date relative",
				    #"ADD year" = Table.AddColumn(#"--Year Columns--", "Year", each Date.Year([Date]), Int64.Type),
				    #"ADD year start date" = Table.AddColumn(#"ADD year", "Year Start Date", each Date.StartOfYear([Date]), type date),
				    #"ADD year relative num" = Table.AddColumn(#"ADD year start date", "Year Relative Num", each Date.Year([Date]) - 
				Date.Year(DateTime.From(DateTime.FixedLocalNow())), Int64.Type),
				    #"ADD fis year" = Table.AddColumn(#"ADD year relative num", "Fis Year", each Date.Year([FisRefDate]), Int64.Type),
				    #"ADD fis year start date" = Table.AddColumn(#"ADD fis year", "Fis Year Start Date", each 
				Date.AddMonths( Date.StartOfYear([FisRefDate]) , -1 * (12 - [LastMonthOfFiscal] ) )
				
				, type date),
				    #"ADD fis year relative num" = Table.AddColumn(#"ADD fis year start date", "Fis Year Relative Num", each [
				vrSysDate = Date.From(DateTime.FixedLocalNow()),
				vrLastMonFY = [LastMonthOfFiscal], 
				
				vrSysEquivDate = 
				    Date.AddMonths( 
				        vrSysDate, 
				        12 - vrLastMonFY 
				    ),
				vrSysFY = Date.Year( vrSysEquivDate ),
				vrRowFY = Date.Year([FisRefDate]),
				vrRelativeFY = vrRowFY - vrSysFY
				][vrRelativeFY], Int64.Type),
				    #"--Qtr Columns--" = #"ADD fis year relative num",
				    #"ADD quarter num" = Table.AddColumn(#"--Qtr Columns--", "Qtr Num", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"ADD quarter" = Table.AddColumn(#"ADD quarter num", "Qtr", each "Q" & Text.From( Date.QuarterOfYear([Date]) ), type text),
				    #"ADD qtr qq-yy" = Table.AddColumn(#"ADD quarter", "Qtr qq-yy", each 
				"Q" & Text.From( Date.QuarterOfYear([Date]) ) & 
				"-" & Date.ToText([Date], "yy"), type text),
				    #"ADD qtr start" = Table.AddColumn(#"ADD qtr qq-yy", "Qtr Start Date", each Date.StartOfQuarter([Date]), type date),
				    #"ADD fis qtr num" = Table.AddColumn(#"ADD qtr start", "Fis Qtr Num", each Date.QuarterOfYear( [FisRefDate] ), type number),
				    #"ADD fis qtr" = Table.AddColumn(#"ADD fis qtr num", "Fis Qtr", each "Q" & Text.From( Date.QuarterOfYear( [FisRefDate]) ), type text),
				    #"ADD fis qtr start date" = Table.AddColumn(#"ADD fis qtr", "Fis Qtr Start Date", each Date.StartOfQuarter([Date]), type date),
				    #"ADD fis qtr qq-yy" = Table.AddColumn(#"ADD fis qtr start date", "Fis Qtr qq-yy", each "Q" & Text.From( Date.QuarterOfYear( [FisRefDate] ) ) & 
				"-" & Date.ToText( [FisRefDate], "yy"), type text),
				    #"ADD qtr relative num" = Table.AddColumn(#"ADD fis qtr qq-yy", "Qtr Relative Num", each
				(
				    Date.Year(Date.From([Date])) * 4 + 
				    Date.QuarterOfYear(Date.From([Date])) 
				) -
				(
				    Date.Year(Date.From(DateTime.FixedLocalNow())) * 4 + 
				    Date.QuarterOfYear(Date.From(DateTime.FixedLocalNow())) 
				),
				type number),
				    #"--Month Columns--" = #"ADD qtr relative num",
				    #"ADD month num" = Table.AddColumn(#"--Month Columns--", "Month Num", each Date.Month([Date]), Int64.Type),
				    #"ADD month" = Table.AddColumn(#"ADD month num", "Month", each Date.ToText( [Date], "MMM" ), type text),
				    #"ADD month mmm-yyyy" = Table.AddColumn(#"ADD month", "Month mmm-yyyy", each Date.ToText( [Date], "MMM-yyyy" ), type text),
				    #"ADD month start date" = Table.AddColumn(#"ADD month mmm-yyyy", "Month Start Date", each Date.StartOfMonth([Date]), type date),
				    #"ADD fis month num" = Table.AddColumn(#"ADD month start date", "Fis Month Num", each Date.Month([FisRefDate]), Int64.Type),
				    #"ADD fis month mmm-yyyy" = Table.AddColumn(#"ADD fis month num", "Fis Month mmm-yyyy", each Date.ToText( [Date], "MMM" ) & "-" & Date.ToText( [FisRefDate], "yyyy" ), type text),
				    #"ADD fis month start date" = Table.AddColumn(#"ADD fis month mmm-yyyy", "Fis Month Start Date", each Date.StartOfMonth([Date]), type date),
				    #"ADD fis month" = Table.AddColumn(#"ADD fis month start date", "Fis Month", each Date.ToText( [Date], "MMM" ), type text),
				    #"ADD relative month num" = Table.AddColumn(#"ADD fis month", "Month Relative Num", each 
				( Date.Year([Date]) * 12 + Date.Month([Date]) )- 
				( Date.Year( Date.From( DateTime.FixedLocalNow() ) ) * 12 + Date.Month(Date.From( DateTime.FixedLocalNow() )) )
				, type number),
				    #"--Week Columns--" = #"ADD relative month num",
				    #"ADD wk of year usa" = Table.AddColumn(#"--Week Columns--", "Week of Year (USA)", each [
				//Get the assumptions
				vrRowDate  = [Date],
				vrYrStartMon = [FirstMonthOfFiscal],
				vrDowStart = [First Day of Wk Num],
				
				//Figure out the FisYrs start date for this row
				vrRowYear  = Date.Year( vrRowDate ),
				vrRefDateRaw = #date( vrRowYear, 1, 1 ),
				
				//Get the first day of the week for each
				vrYrWkStart = Date.StartOfWeek( vrRefDateRaw, vrDowStart ),
				vrRowWkStart = Date.StartOfWeek( vrRowDate, vrDowStart ),
				
				//Get the days between and divide by 7 to get wks between.
				vrWeekNum = 
				    Duration.Days(  vrRowWkStart - vrYrWkStart ) 
				    / 7 
				    + 1
				][vrWeekNum], type number),
				    #"ADD we start date" = Table.AddColumn(#"ADD wk of year usa", "Week Start Date", each Date.StartOfWeek([Date], [First Day of Wk Num]), type date),
				    #"ADD fis wk of year usa" = Table.AddColumn(#"ADD we start date", "Fis Week Of Year (USA)", each [
				//Get the assumptions
				vrRowDate  = [Date],
				vrYrStartMon = [FirstMonthOfFiscal],
				vrDowStart = [First Day of Wk Num],
				
				//Figure out the FisYrs start date for this row
				vrRowMonth = Date.Month( vrRowDate ),
				vrRowYear  = Date.Year( vrRowDate ),
				vrDateInCurrCalYear = ( vrRowMonth >= vrYrStartMon ),
				vrRefDateRaw =
				    if   vrDateInCurrCalYear
				    then #date( vrRowYear,     vrYrStartMon, 1 )
				    else #date( vrRowYear - 1, vrYrStartMon, 1 ),
				
				//Get the first day of the week for each
				vrYrWkStart = Date.StartOfWeek( vrRefDateRaw, vrDowStart ),
				vrRowWkStart = Date.StartOfWeek( vrRowDate, vrDowStart ),
				
				//Get the days between and divide by 7 to get wks between.
				vrWeekNum = 
				    Duration.Days(  vrRowWkStart - vrYrWkStart ) 
				    / 7 
				    + 1
				][vrWeekNum], type number),
				    #"ADD wk relative" = Table.AddColumn(#"ADD fis wk of year usa", "Week Relative", each [
				vrRowDate = [Date],
				vrSysDate = Date.From( DateTime.FixedLocalNow() ),
				vrWeeksStart = [First Day of Wk Num],
				
				vrRowWkStart = Date.StartOfWeek( vrRowDate, vrWeeksStart ),
				vrSysWkStart = Date.StartOfWeek( vrSysDate, vrWeeksStart ),
				vrRelativeWeek = 
				    Duration.Days( vrRowWkStart - vrSysWkStart ) / 7
				][vrRelativeWeek], type number),
				    #"ADD day of wk name" = Table.AddColumn(#"ADD wk relative", "Day of Week", each Date.ToText([Date], "ddd"), type text),
				    #"ADD day of wk num" = Table.AddColumn(#"ADD day of wk name", "Day of Wk Num", each Date.DayOfWeek( [Date], [First Day of Wk Num] ) + 1, Int64.Type),
				    #"ADD weekday flag" = Table.AddColumn(#"ADD day of wk num", "Weekday Flag", each if Date.DayOfWeek( [Date], Day.Monday ) <= 4
				then 1
				else 0, Int64.Type),
				    #"ADD weekday label" = Table.AddColumn(#"ADD weekday flag", "Weekday Label", each if Date.DayOfWeek( [Date], Day.Monday ) <= 4
				then "Weekday"
				else "Weekend", type text),
				    #"DELETE helper columns" = Table.RemoveColumns(#"ADD weekday label",{"First Day of Wk Num", "LastMonthOfFiscal", "FirstMonthOfFiscal", "FisRefDate"}),
				    #"--Keep Reorder Rename--" = #"DELETE helper columns"
				in
				    #"--Keep Reorder Rename--"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

